name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang, msvc]
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: macos-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: msvc
    name: ${{ matrix.os }} - ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake

      - name: Configure MSVC environment
        if: matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure Clang to use libc++
        if: matrix.os == 'macos-latest'
        run: |
          export CXX=clang++
          export CC=clang
          cmake -B build -S . -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-stdlib=libc++"  
      - name: Configure project
        if: matrix.os != 'macos-latest'
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
